version: '3.9'

services:
  web:
    image: nginx:latest
    volumes:
    - ./Server:/var/www/html
    - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_ff_ftw
      MYSQL_DATABASE: apws
      MYSQL_USER: ff
      MYSQL_PASSWORD: askldjeimghhgwese
    volumes:
      - "./Server/database/structure.sql:/docker-entrypoint-initdb.d/1.sql"